---
- name: Stop BioFoundry Podman Containers
  hosts: raspberry_pis
  tasks:
    - name: Ensure the BioFoundry directory exists
      file:
        path: /home/open/BioFoundry
        state: directory
        owner: open
        group: open
        mode: "0755"

    - name: Stop Podman containers
      command: podman-compose down
      args:
        chdir: /home/open/BioFoundry
